#!/bin/bash
version=1.0
if [ $# = 0 ]
then
	echo "No parameters specified."
	echo "Usage: colash keyword; 'colash help' for list of keywords"

#Make the bash short
elif [ $1 == 'short' ]
then
	export PS1='\u@\h $ '
	echo "Bash Shortened!"
#Make the bash ultra-short
elif [ $1 == 'sshort' ]
then
	export PS1='$ '
	echo "Bash Super-Shortened!"

elif [ $1 == 'lgit' ] 
then
	export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\]:\w\[\033[31m\]$(__git_ps1 "(%s)")\[\033[01;34m\]$\[\033[00m\] '
	echo "Git Long form!" 

elif [ $1 == 'sgit' ] 
then
	export PS1='\W\[\033[31m\]$(__git_ps1 "(%s)")\[\033[00m\]$ '	
	echo "Git Short form!" 


elif [ $1 == 'default' ] 
then
	export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '	
	echo "Default setting!" 

elif [ $1 == 'help' ] 
then
	echo "colash version $version"
	echo "Valid Keywords:"
	echo "short	:	User@Host"
	echo "sshort	:	Just a '>'"	
	echo "lgit	:	Full Path with Git branch"	
	echo "sgit	:	Dir Name with Git Branch"
	echo "default	:	User@host and path"
	echo "help	:	Display this list"
else
	echo "Undefined command. Try 'colash help'"
fi

# Sample syntax for changing color of the bash prompt:
# export PS1='\[\033[01;32m\]\h\[\033[01;34m\] \w\[\033[31m\]$(__git_ps1 "(%s)") \[\033[01;34m\]$\[\033[00m\] '
# from: https://makandracards.com/makandra/524-show-the-current-git-branch-on-your-bash-prompt
