#!/bin/bash

# Linux unlock gnome keyring
# From https://unix.stackexchange.com/a/676655

function unlock-keyring ()
{
    read -rsp "Password: " pass
    export $(echo -n "$pass" | gnome-keyring-daemon --replace --unlock)
    unset pass
}

echo "This function will unlock the gnome keyring for use on a terminal"
unlock-keyring
