#!/bin/bash
sleep 60
notify-send -t 2000 -u normal "Starting Keymap Reconfigurator" "Please stop using keyboard"
sleep 5
xmodmap /path/to/.xmodmap_file
notify-send -t 2000 -u critical "Completed Keymap Reconfigurator" "Printscr is now menu Key"
